version: '3.8'

services:
  managep:
    build: ./
    command: ./app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5437
      - DB_PASSWORD=muhit9845

  db:
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muhit9845
    ports:
      - "5437:5432"